export { default as Home } from "./Home/Home";
export { default as About } from "./About/About";
export { default as Footer } from "./Footer/Footer";
export { default as Problems } from "./Problems/Problems";
export { default as Nav } from "./Nav/Nav";
export { default as FakeNav} from "./FakeNav/FakeNav";
export { default as Mission } from "./Mission/Mission";
export { default as Plan } from "./Plan/Plan";
export {default as Solution } from "./Solution/Solution";
export {default as Team } from "./Team/Team";
export {default as NotFound} from "./NotFound/NotFound";
